### ISSUE TITLE
Pretrained_model is missing

### ISSUE THREAD

**Issue by whw-alex** [HWPengSYSU1993/Domain-private-Factor-Detachment-Network#1]
File 'DFD_method.py', line 2017 writes 
_parser.add_argument('--pretrained_model', type=str,
        help='Load a pretrained model before training starts.', default='./models/Resnet50_CBAM_160_256dims_182_44_minePretrained_20201013/LFW_BEST/')_

But I cannot find it.  Please tell me where the pretrained_model is, thanks!

**Comment by hwpengTristin** [comment]
Thank you for your interest. The pretrained model is released as follow:

Link: https://pan.baidu.com/s/133QLNTn9SiQ0CLqg_IsE4g 
Extraction Code: 0131

**Comment by whw-alex** [comment]
> Thank you for your interest. The pretrained model is released as follow:
> 
> Link: https://pan.baidu.com/s/133QLNTn9SiQ0CLqg_IsE4g Extraction Code: 0131

Thank you so much!
